### ISSUE TITLE
Tutorial #1: Load public data, create a graph and run a library method

### ISSUE THREAD

**Issue by vasia** [vasia/flink-graph#3]
The first tutorial should explain the graph creation methods in Gelly. We can use a publicly available graph dataset (e.g. [SNAP](http://snap.stanford.edu/data/index.html), [Konnect](http://konect.uni-koblenz.de/networks/)) to read a file of edges, create, and initialize a graph in Gelly.
Then, we show how to run a library algorithm on the graph, e.g. SSSP or PageRank, using the `run()` method.

**Comment by vasia** [comment]
Here's some feedback on tutorial 1:
- “let’s get to coding section”: move to intro / tutorial 0
- explain a bit the first example
- explain the purpose of the tutorial
- in "Steps to follow": make a concrete example. Choose the dataset and one method to read it. If you want to explain all ways to load a graph, this should be explained before. The example in fromDataSet, fromCollection, fromTupleDataSet do not refer to the chosen Twitter dataset and this is confusing.

**Comment by vasia** [comment]
I see that there's still no concrete example of actually loading the twitter dataset and running the method on it..? You refer to it, but then you introduce all graph creation methods. We should only explain the one we use for this data. It's just an edge list of ids separated by tabs, no?

**Comment by vasia** [comment]
The first figure is a bit blurry. I would prefer all code to be properly written and not hand-written actually. We can keep the edge drawing, that's nice ;)

**Comment by samk3211** [comment]
What do you really mean by "concrerte example"? I loaded the twitter data set for all creation methods, that's why i refer to all of them.  All use it as input. This was just to show the different possibilities provided by Gelly. Aren't these concrete example? 

I had created the graph separately using the three methods starting from the twitter data set and that's why then i show also the statistics part for all of them in tutorial2.

**Comment by samk3211** [comment]
yes, i know that some figures are blurry. Had told you that will update them
